FROM ubuntu
RUN  apt-get update \
  && apt-get install -y openssh-server \
  && apt-get install -y git \
  && rm -rf /var/lib/apt/lists/*
COPY init.sh /
EXPOSE 22
RUN service ssh start
ENTRYPOINT /init.sh
